### ISSUE TITLE
请问您有原论文Pdf吗？

### ISSUE THREAD

**Issue by ro4tub** [guidao/Characterizing-the-Scalability-of-Erlang-VM-on-Many-core-Processors#1]
原有的论文链接已经失效，能否分享一下？
谢谢。

**Comment by guidao** [comment]
http://www.diva-portal.org/smash/get/diva2:392243/FULLTEXT01.pdfOn
这个还挺好找。

**Comment by ro4tub** [comment]
链接能找到，但是打不开。您能打开？

**Comment by guidao** [comment]
可以啊。

**Comment by ro4tub** [comment]
我几种方式都不能打开额。也请几个朋友做了测试，也不行。
能不能发我一下，多谢了。
ro4tub_AT_gmail.com

**Comment by guidao** [comment]
加到仓库里了。

**Comment by ro4tub** [comment]
非常感谢！
